# This workflow is prepared to be executed manually. User should use the "Use workflow from" built-in dropdown
# provided by GitHub to select the git tag (docker image) to deploy. This value is provided by github.ref_name
name: Production Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout
  pull-requests: write

jobs:
  deploy_prod:
    name: Production
    uses: trafilea/trafilea-reusable-workflows/.github/workflows/deploy_terragrunt.yaml@main
    with:
      APP_NAME: go-template
      ENVIRONMENT: prod
      DOCKER_IMAGE_TAG: ${{ github.ref_name }}
    secrets: inherit

  upload_env_vars:
    name: Environment vars
    uses: trafilea/trafilea-reusable-workflows/.github/workflows/s3_upload_env_file.yaml@main
    needs: deploy_prod
    with:
      APP_NAME: go-template
      DOCKER_IMAGE_TAG: ${{ github.ref_name }}
      ENV_FILE_TYPE: all
    secrets:
      GH_WORKFLOW_TOKEN: ${{ secrets.GH_WORKFLOW_TOKEN }}
      OIDC_IAM_ROLE: ${{ secrets.OIDC_IAM_ROLE }}

  argocd_prod:
    name: ArgoCD Production
    uses: trafilea/trafilea-reusable-workflows/.github/workflows/argocd_deployment.yaml@main
    needs: upload_env_vars
    with:
      APP_NAME: go-template
      ENVIRONMENT: prod
      DOCKER_IMAGE_TAG: ${{ github.ref_name }}
    secrets:
      GH_WORKFLOW_TOKEN: ${{ secrets.GH_WORKFLOW_TOKEN }}
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_PROD_GITHUB }}
      OIDC_IAM_ROLE: ${{ secrets.OIDC_IAM_ROLE }}
